fastscape-lem/fastscapelib

doc/source/api_cpp.rst
include/fastscapelib/consts.hpp
include/fastscapelib/flow_routing.hpp
include/fastscapelib/sinks.hpp
include/fastscapelib/utils.hpp

Split implementation (in `fastscapelib::detail` namespace) and API functions (in `fastscapelib` namespace), as suggested [here](https://github.com/QuantStack/xtensor/pull/867#issuecomment-392526275).
Use xt::xexpression in API (to be replaced by a shaped expression -- see https://github.com/QuantStack/xtensor/pull/867).
`index_t` is now an alias of `std::ptrdiff_t` (instead of `int64_t` previously). Maybe replace this with `xt::index_t` if/when it is ready (see https://github.com/QuantStack/xtensor/pull/661).

Better xtensor style compatibility

---

.gitignore
.travis.yml
python/fastscapelib/tests/test_flow_routing.py
python/fastscapelib/tests/test_sinks.py
python/src/main.cpp

Uses pytest.
It seems a bit silly to duplicate tests here, but I don't see other ways to have reliable tests for Python bindings. Edges cases should still be tested only in the C++ test suite.

Add tests for Python bindings

---

include/fastscapelib/flow_routing.hpp
include/fastscapelib/sinks.hpp
test/test_flow_routing.cpp
test/test_sinks.cpp

Fixes #14.
`fastscapelib`  is kept as namespace (no abbreviation is used).

Fix fastscapelib namespace in headers

---

.appveyor.yml
README.rst
include/fastscapelib/bedrock_channel.hpp
python/fastscapelib/tests/test_flow_routing.py
test/CMakeLists.txt

TODO:
Maybe for later: google-test is installed using conda (built in release mode I guess), which probably causes the MSVC linking error if tests are not built in release mode too. So we build here in release mode. It's probably not the best solution, but at least there is no error. An alternative could be building google-test from source in debug mode? Or maybe the real issue is static vs. dynamic linking to google-test?

Configure Appveyor

---

benchmark/CMakeLists.txt
benchmark/benchmark_bedrock_channel.cpp
benchmark/benchmark_hillslope.cpp
benchmark/benchmark_setup.hpp
doc/source/api_cpp.rst
include/fastscapelib/bedrock_channel.hpp
python/fastscapelib/tests/test_bedrock_channel.py
python/src/main.cpp
test/test_bedrock_channel.cpp
test/test_hillslope.cpp

``k_coef`` argument should now accepts either a scalar or a (1-d or 2-d) array.
TODO:

Support spatially variable stream-power-law coefficient

---

.travis.yml
include/fastscapelib/hillslope.hpp

Some fixes + CI settings to ensure that the fastscapelib Python library will compile on older apple-clang versions (e.g., the one used by conda-forge).
This test is allowed to fail on travis, as hopefully conda-forge will soon use more recent compilers.

Fix old apple-clang versions (Python bindings)

---

doc/source/install.rst
include/fastscapelib/bedrock_channel.hpp
include/fastscapelib/flow_routing.hpp
include/fastscapelib/hillslope.hpp
python/src/main.cpp

Don't merge until xtensor 0.18 is released (and new release for xtensor-python too).
TODO:

Update to xtensor latest version (0.18)

---

.travis.yml
CMakeLists.txt
doc/source/build_options.rst
doc/source/release_notes.rst
downloadXTensor.cmake.in

This PR adds the possibility to configure fastscapelib build so that xtensor is downloaded from github (master):
```
$ cmake -DDOWNLOAD_XTENSOR=ON ..
```
This is useful for CI testing against development version of xtensor (added as xfail to travis).

Build fastscapelib using xtensor master (cmake option)

---

CMakeLists.txt
benchmark/CMakeLists.txt
benchmark/benchmark_grid.cpp
include/fastscapelib/fastscapelib.hpp
include/fastscapelib/profile_grid.hpp
include/fastscapelib/structured_grid.hpp
include/fastscapelib/xtensor_utils.hpp
python/fastscapelib/tests/test_grid.py
python/src/grid.cpp
python/src/main.cpp
python/src/modelings.cpp
test/CMakeLists.txt
test/test_profile_grid.cpp

Description
--
Add an interface structured grid and a first implementation named `profile_grid` which is a 1D grid.
This PR is broadly inspired by #42 .
Details:
- add interface for structured grid 
- add profile (1D) grid
- add python bindings using `pybind11`
- add tests (`googletest` and `pytest`) and benchmarks (`google/benchmark`)
- generate cmake targets for each test and benchmark to use development
This PR needs to be rebased after #49 merging.

Add interface and profile (1d) grids

---

benchmark/benchmark_profile_grid.cpp
benchmark/benchmark_raster_grid.cpp
include/fastscapelib/profile_grid.hpp
include/fastscapelib/raster_grid.hpp
include/fastscapelib/structured_grid.hpp
python/fastscapelib/tests/test_profile_grid.py
python/src/grid.cpp
test/test_profile_grid.cpp
test/test_raster_grid.cpp

Add caching of nodes neighbors indices for structured grids.
At this time, the neighbors computation uses caching from both:
- derived classes/grids for the distances and node status (specific implementations)
- base class/grid for indices (generic implementation)
This will allow to iterate efficiently over nodes and their neighbors.
Extract from the benchmarks:
```
Run on (8 X 2304.01 MHz CPU s)
2020-12-28 17:11:57
--------------------------------------------------------------------------------------------------------------------
Benchmark                                                                             Time           CPU Iterations
-------------------------------------------------------------------------------------------------------------------- …
```

Grid caching

---

benchmark/CMakeLists.txt
benchmark/benchmark_flow_routing.cpp
include/fastscapelib/flow_routing.hpp
include/fastscapelib/utils.hpp
test/test_flow_routing.cpp

First implementation of a generic flow routing algorithm `compute_receivers` using the `structured_grid` API, the `profile_grid` and `raster_grid` and the caching of neighbors (PRs #51 #53 #54).
The `compute_receivers` can now handle any grid conforming to the `structured_grid` interface.
The caching of neighbors allows better performances than the current `compute_receivers_d8` when the cache is warmed-up (~15% faster), and only slightly slower when the cache is not computed yet (~5% slower).
```
Run on (8 X 2304.01 MHz CPU s)
2020-12-31 14:55:24
--------------------------------------------------------------------------------------------------------------------
Benchmark                                                                             Time           CPU Iterations …
```

Generic `compute_receivers` flow routing algo

---

benchmark/benchmark_flow_routing.cpp
benchmark/benchmark_profile_grid.cpp
benchmark/benchmark_raster_grid.cpp
include/fastscapelib/flow_routing.hpp
include/fastscapelib/profile_grid.hpp
include/fastscapelib/raster_grid.hpp
include/fastscapelib/structured_grid.hpp
test/test_profile_grid.cpp
test/test_raster_grid.cpp

Improve neighbors indices caching for structured grids.
Clean the code and implement a no-caching policy.
Details:
- add `store` and `get_storage` methods to caches
- add a `neighbors_no_cache` policy
- check that cache width is large enough
- change API of neighbors method for callers to provide a ref to fill
- minor updates of tests and benchs due to API changes

Improve neighbors indices caching

---

include/fastscapelib/profile_grid.hpp
include/fastscapelib/raster_grid.hpp
include/fastscapelib/structured_grid.hpp
python/fastscapelib/tests/test_profile_grid.py
python/fastscapelib/tests/test_raster_grid.py
python/src/grid.cpp
test/test_profile_grid.cpp
test/test_raster_grid.cpp

Add a `length` method to get the physical length of the grid in all its dimensions.
Related to #59.
Details:
- add factory method `from_length`
- add tests for profile and raster grids
- fix ICE (internal compiler error) on MSVC14.0 (VS2015)

Add grid length

---

test/CMakeLists.txt

Improve CMake configuration for C++ tests to fit with latest `gtest` versions.
It fixes a build error with msvc when downloading `gtest` from sources.

Fix tests with msvc using `gtest` sources

---

benchmark/benchmark_flow_routing.cpp
benchmark/benchmark_profile_grid.cpp
benchmark/benchmark_raster_grid.cpp
benchmark/benchmark_setup.hpp
include/fastscapelib/flow_routing.hpp
include/fastscapelib/hillslope.hpp
include/fastscapelib/profile_grid.hpp
include/fastscapelib/raster_grid.hpp
include/fastscapelib/sinks.hpp
include/fastscapelib/structured_grid.hpp
include/fastscapelib/utils.hpp
include/fastscapelib/xtensor_utils.hpp
test/CMakeLists.txt
test/test_flow_routing.cpp
test/test_raster_bishop_grid.cpp
test/test_raster_grid.cpp
test/test_raster_grid.hpp
test/test_raster_queen_grid.cpp
test/test_raster_rook_grid.cpp

This PR is a major refactoring of `raster_grid` class. It is related to #61.
The `raster_connect` is now a template parameter, which allow optimization of the neighbors indices cache based on fixed size objects.
Capability to easily access neighbors from the class `raster_connect` to an other is preserved using the newly introduced `create_similar_raster` template method:
```cpp
using grid_type = fs::raster_grid_xt<fs::xtensor_selector, fs::raster_connect::queen>;
using shape_type = typename grid_type::shape_type;
shape_type shape {{5, 10}};
grid_type queen_grid = grid_type(shape, {1.3, 1.2}, node_status::fixed_value_boundary);
auto rook_grid = queen_grid.create_similar_raster<raster_connect::rook>();
```
Improved readability of benchmarks:
- reduce number of tested size, but increase …

Improved raster grids

---

include/fastscapelib/structured_grid.hpp
test/test_raster_bishop_grid.cpp
test/test_raster_grid.hpp
test/test_raster_queen_grid.cpp
test/test_raster_rook_grid.cpp

Description
--
Iterate over a `grid` node `neighbors_indices` reusing the same container passed by reference.
Related to #71 .
Details:
- add an overload to `structured_grid::neighbors_indices` method
- test on all raster grids

Extend neighbors indices api

---

benchmark/benchmark_flow_routing.cpp
include/fastscapelib/fastscapelib.hpp
include/fastscapelib/flow_router.hpp
include/fastscapelib/iterators.hpp
include/fastscapelib/structured_grid.hpp
test/CMakeLists.txt
test/test_profile_grid.cpp
test/test_structured_grid.cpp

Description
--
Add iterators for `nodes_indices`, accepting filter on `node_status`.
Improve API of `neighbors_indices` and `neighbors` methods of `structured_grid` to allow the following syntax:
```cpp
neighbors_type neighbors;
neighbors_indices_type neighbors_indices;
for (auto i : grid.nodes_indices())
{
for (auto n : grid.neighbors(i, neighbors))
{          
// do something
}
for (auto n : grid.neighbors_indices(i, neighbors_indices))
{          
// do something
}
}
```
Related to #71

Add iterators

---

include/fastscapelib/flow_router.hpp
test/test_flow_graph.cpp

Description
--
The `single_flow_router` class needs to clean the `donors_count` variable of the `flow_graph` before to re-execute.
It fixes wrong accesses to arrays causing segfault.

Fix memory effect

---

python/fastscapelib/tests/test_profile_grid.py
python/fastscapelib/tests/test_raster_grid.py
python/src/grid.cpp

Description
--
Add the `Grid.shape` property to Python bindings (both `ProfileGrid` and `RasterGrid`).

Grid shape python binding

---

benchmark/benchmark_bedrock_channel.cpp
include/fastscapelib/bedrock_channel.hpp
include/fastscapelib/flow_graph.hpp
include/fastscapelib/structured_grid.hpp
python/fastscapelib/tests/test_bedrock_channel.py
python/fastscapelib/tests/test_flow_graph.py
python/fastscapelib/tests/test_profile_grid.py
python/src/flow_graph.cpp
python/src/flow_graph.hpp
python/src/grid.cpp
python/src/modelings.cpp
test/test_bedrock_channel.cpp
test/test_flow_graph.cpp

Description
--
Refactor the `erode_stream_power` algo to use `grid` and `flow_graph` API.
Details:
- add an overload to `flow_graph::accumulate` to pass a scalar to broadcast
- update python bindings
- update benchmarks
- update c++ and python tests

Refactor erode stream power algo

---

python/src/flow_graph.cpp
python/src/flow_graph.hpp
python/src/modelings.cpp
python/src/pytensor_utils.hpp

Description
--
Use `xt::layout_type::row_major` for `xt::pyarray` in Python bindings to improve `erode_stream_power` algo performance.
This is related to the use of `xt::flatten` to provide a flat view of pyarrays.

Improve erode stream power performance

---

CMakeLists.txt

…, structured_grid.hpp, and extensor_utils.hpp
I hope I did this right, I compiled a C++ file with this fastscape version and it worked then ran.

Rearraged headers alphabetically + added missing ones

---

include/fastscapelib/flow_graph.hpp
include/fastscapelib/flow_router.hpp
include/fastscapelib/grid.hpp
include/fastscapelib/sink_resolver.hpp
include/fastscapelib/unstructured_mesh.hpp
test/test_flow_graph.cpp
test/test_sink_resolver.cpp

The new workflow for updating flow routes is:
```cpp
auto new_elevation = sink_resolver->resolve1(elevation, flow_graph);
flow_router->route1(new_elevation, flow_graph);
auto final_elevation = sink_resolver->resolve2(new_elevation, flow_graph);
flow_router->route2(final_elevation, flow_graph);
```
The 2nd route method allows supporting the approach used in [fastscapelib-fortran](https://github.com/fastscape-lem/fastscapelib-fortran) for multiple direction flow routing:
- `resolve1`: do nothing 
- `route1`: compute single flow routing
- `resolve2`:
- update flow paths to resolve flow trapped in closed depressions (Cordonnier et al. algorithm) 
- update elevation (fill closed depressions with a tiny slope) over one traversal of the flow-graph formed by the updated (single) flow paths
- …

Refactor router and resolver implementation methods

---

benchmark/benchmark_profile_grid.cpp
benchmark/benchmark_raster_grid.cpp
include/fastscapelib/grid.hpp
include/fastscapelib/raster_grid.hpp
include/fastscapelib/sinks.hpp
python/fastscapelib/tests/test_raster_grid.py
python/src/grid.cpp
python/src/grid.hpp
test/test_raster_queen_grid.cpp

Clean-up raster_grid class

---

benchmark/benchmark_flow_routing.cpp
benchmark/benchmark_profile_grid.cpp
benchmark/benchmark_raster_grid.cpp
include/fastscapelib/flow/flow_graph.hpp
include/fastscapelib/grid/base.hpp
include/fastscapelib/grid/profile_grid.hpp
include/fastscapelib/grid/raster_grid.hpp
include/fastscapelib/grid/unstructured_mesh.hpp
include/fastscapelib/utils/xtensor_utils.hpp
python/src/flow_graph.cpp
python/src/flow_graph.hpp
python/src/flow_router.hpp
python/src/grid.hpp
python/src/pytensor_utils.hpp
python/src/sink_resolver.hpp
test/test_flow_router.cpp
test/test_profile_grid.cpp
test/test_raster_grid.cpp
test/test_raster_grid.hpp
test/test_single_flow_router.cpp
test/test_structured_grid.cpp

`xt_container` has now two members `array_type` and `tensor_type`. Either one or the other might be picked from the selector (needed in some cases).

Use one selector for array and tensor types

---

benchmark/CMakeLists.txt
benchmark/benchmark_single_flow_router.cpp
include/fastscapelib/eroders/spl.hpp
include/fastscapelib/flow/flow_graph.hpp
include/fastscapelib/flow/flow_graph_impl.hpp
include/fastscapelib/flow/flow_router.hpp
python/fastscapelib/tests/test_flow_graph.py
python/fastscapelib/tests/test_flow_router.py
python/src/flow_graph.cpp
python/src/flow_graph.hpp
test/test_flow_router.cpp
test/test_single_flow_router.cpp
test/test_spl.cpp

- add single flow router benchmark
- non-recursive implementation of dfs graph traversal
- rename `dfs_stack` -> `dfs_indices` 
- single flow: no need to create receiver arrays of shape `(grid_size, n_neighbors_max)`, use shape `(grid_size, 1)` instead

Single flow router tweaks

---

azure-pipelines.yml
python/src/grid.cpp
python/src/grid.hpp

- use lambdas for all properties (directly using class method references was sometimes causing issues, e.g., with GCC 11)
- rename registration helper functions
(cherry picked from #112)

Refactor python grid properties registration

---

doc/source/release_notes.md
include/fastscapelib/flow/flow_graph.hpp
include/fastscapelib/flow/flow_operator.hpp
include/fastscapelib/flow/flow_snapshot.hpp
python/fastscapelib/tests/test_flow_snapshot.py
python/src/flow_graph.cpp
python/src/flow_graph.hpp

The `return_value_policy` of `FlowGraph.impl()` wasn't the right one.

Fix segfault when accessing graph snapshot implementation members (Python bindings)

---

.github/workflows/python-wheels.yml
.github/workflows/tests.yml
CMakeLists.txt
doc/environment.yml
doc/source/api_python/hidden.rst
doc/source/install.md
environment-python-dev.yml
include/fastscapelib/flow/flow_graph.hpp
include/fastscapelib/utils/thread_pool.hpp
pyproject.toml
python/fastscapelib/eroders/flow_kernel_eroder.py
python/fastscapelib/flow/__init__.py
python/fastscapelib/flow/__init__.pyi
python/fastscapelib/flow/numba/__init__.py
python/fastscapelib/flow/numba/flow_kernel.py
python/fastscapelib/flow/numba_flow_kernel.py
python/fastscapelib/tests/test_flow_kernel.py
python/src/flow_graph.cpp

Follow https://scientific-python.org/specs/spec-0000/ for both Python and Numpy.
Build wheels against Numpy 2.x so it works with both Numpy 1.xx and 2.x (isolated builds only... for conda-forge it relies on pinned versions and migrations). 
Make Numba dependency optional (it often requires some time before it supports last Python versions).
TODO:

Bump Python / Numpy supported versions

---

.github/codecov.yml
.github/dependabot.yml
.github/release.yml
.github/workflows/python-wheels.yml
.github/workflows/tests.yml
.readthedocs.yml
doc/environment.yml
environment-dev.yml
environment-python-dev.yml
pixi.lock
pixi.toml
pyproject.toml
python/fastscapelib/flow/numba/flow_kernel.py

- Pin xtensor: this is safer (https://github.com/xtensor-stack/xtensor/pull/2829https://github.com/xtensor-stack/xtensor/pull/2829)
- Fix doc builds on RTD
- Update pixi configuration: add cxx-compiler and update lockfile (https://github.com/prefix-dev/pixi/issues/3479)
- CI: remove Ubuntu  20.04 from Python test matrix, update python wheels build config

MNT: pin xtensor, fix RTD, update pixi conf

---

CMakeLists.txt
doc/source/install.md

If xtensor is not in a standard directory, allow specifying `-DXTENSOR_DIR=...` on the cmake command line.

Provide hints where CMake should find xtensor.

---

include/fastscapelib/eroders/spl.hpp

It is not necessary to end a function definition with a semicolon -- the closing brace already does that. Some compilers warn about the semicolon, so let's remove it.

Avoid warnings about unnecessary semicolons.

---

include/fastscapelib/flow/flow_graph_impl.hpp

Some compilers are more lenient with the number of braces necessary to initialize arrays, and others are not. Mine is not. So add the missing braces.

Add a set of missing braces.

---

doc/source/api_cpp/grid.rst
include/fastscapelib/grid/trimesh.hpp
python/src/grid.hpp
test/test_trimesh.cpp

And remove the `trimesh` type alias.
So we're now consistent with other grid classes in C++ API (changes made in #155).

Rename trimesh_xt -> trimesh
